name: ZAP DAST Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build API image
        run: docker build -t api-image .

      - name: Run API container
        run: |
          docker run -d --name api \
            -p 5000:5000 api-image
          sleep 15

      - name: Pull ZAP image
        run: docker pull ghcr.io/zaproxy/zaproxy:stable

      - name: Run ZAP Baseline Scan
        run: |
          mkdir -p zap-report
          chmod -R 777 zap-report
          docker run --rm \
            --network="host" \
            -v "${{ github.workspace }}/zap-report:/zap" \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
              -t http://localhost:5000/swagger/index.html \
              -r zap-report.html \
              -I
        continue-on-error: true

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report/zap-report.html
